### PR TITLE
BLD: Reorganize files and use CMake for all builds

### PR DESCRIPTION
**Pull request by carterbox**
Separates the ptycholib files from the ptychopy file. Switches the ptychopy build system from disutils to a scikit-build/CMake system that shares build targets with ptycholib. Removes duplicate data files. Builds the CUDA and CXX source for ptycholib as one build target instead of two. Enumerates all source files instead of using GLOB because enables more efficient rebuild behavior.

- [ ] Is there a better way to link the two CMake projects instead of using internal cache / add_definitions?
- [ ] Are all the target build properties correct?

### CODE REVIEW

**Comment by carterbox** [comment]
@kyuepublic, do you have tests for the CXX interface that do not require inputs? When I try to run the `testEPIE.cpp` I get, but I don't know what arguments to provide for it.

```
(ptychopy) bash-4.4$ ./ptycho 
ScanMesh(0,0) initialized...
Sample initialized...
Probe initialized...
Could not find data path parameter!
Did you forget to provide `-fp` argument?
free(): invalid pointer
Aborted (core dumped)
```

I have a similar experience with the python epie.py example. It runs, but ends with a seg fault.

```
ePIE Iteration [00058] --- RMS= 0.000000e+00
ePIE Iteration [00059] --- RMS= 0.000000e+00
ePIE Iteration [00060] --- RMS= 0.000000e+00
ePIE Iteration [00061] --- RMS= 0.000000e+00
ePIE Iteration [00062] --- RMS= 0.000000e+00
ePIE Iteration [00063] --- RMS= 0.000000e+00
ePIE Iteration [00064] --- RMS= 0.000000e+00
io=0.027194	phase=41.282304	Done!!
Writing final reconstruction (514,514) to disk...
Segmentation fault (core dumped)
```

**Comment by kyuepublic** [comment]
Yes, for C++ interface, you can try the following command:
./ptycho -jobID=sim256rDM -algorithm=ePIE -beamSize=110e-9 -scanDims=30,30 -step=50e-9,50e-9 -i=100 -size=256 -lambda=2.4796837508399954e-10 -dx_d=172e-6 -z=1 -simulate=1
It will use a simulation image included in the data folder.

**Comment by kyuepublic** [comment]
And you have to have a data folder which have all the simulation images in the same folder where you run the C++ binary. In this case, if you run C++ interface under ptycholib, you have to have a data folder there which includes all the simulation image which you are gonna need. And that is why there are two data folders, which are for testing convenience.

**Comment by carterbox** [comment]
I built ptychoib from keyuepublic:master. I get a similar behavior where the RMS is always zero and the program ends with a segfault.
```
ePIE Iteration [00096] --- RMS= 0.000000e+00
ePIE Iteration [00097] --- step time= 0.108948s
ePIE Iteration [00097] --- RMS= 0.000000e+00
ePIE Iteration [00098] --- step time= 0.108771s
ePIE Iteration [00098] --- RMS= 0.000000e+00
ePIE Iteration [00099] --- step time= 0.109108s
ePIE Iteration [00099] --- RMS= 0.000000e+00
ePIE Iteration [00100] --- step time= 0.108800s
ePIE Iteration [00100] --- RMS= 0.000000e+00
io=0.027178	phase=10.720523	Done!!
Writing final reconstruction (514,514) to disk...
Walltime:16.765475
Segmentation fault (core dumped)
```
Here is the build output from keyuepublic:master. Does anything look incorrect?

```bash
(ptychopy) bash-4.4$ cmake ../src/ -DHDF5_PATH=/home/beams4/DCHING/Documents/ptychopy/dependLib/hdf5-1.8.13
-- Change Dir: /home/beams4/DCHING/Documents/ptychopy/bin/CMakeFiles/CMakeTmp

Run Build Command(s):/bin/gmake -f Makefile cmTC_44595/fast && /bin/gmake  -f CMakeFiles/cmTC_44595.dir/build.make CMakeFiles/cmTC_44595.dir/build
gmake[1]: Entering directory '/home/beams4/DCHING/Documents/ptychopy/bin/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_44595.dir/cudaComputeCapability.cpp.o
/bin/c++  -I/usr/local/cuda/include  -o CMakeFiles/cmTC_44595.dir/cudaComputeCapability.cpp.o -c /home/beams4/DCHING/Documents/ptychopy/src/tools/cudaComputeCapability.cpp
Linking CXX executable cmTC_44595
/home/beams4/DCHING/miniconda3/envs/ptychopy/bin/cmake -E cmake_link_script CMakeFiles/cmTC_44595.dir/link.txt --verbose=1
/bin/c++ -rdynamic CMakeFiles/cmTC_44595.dir/cudaComputeCapability.cpp.o -o cmTC_44595  -Wl,-rpath,/usr/local/cuda/lib64 /usr/local/cuda/lib64/libcudart.so 
gmake[1]: Leaving directory '/home/beams4/DCHING/Documents/ptychopy/bin/CMakeFiles/CMakeTmp'


-- CUDA COMPUTE CAPABILITY: 6.1
-- SDL2_PATH not set: the package will be built without SDL2 visualization support. SDL2 can be downloaded at http://www.libsdl.org/
-- DIY_PATH not set: the package will be built without DIY2 support. Instructions to download DIY2 can be found at https://github.com/diatomic/diy2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/beams4/DCHING/Documents/ptychopy/bin
(ptychopy) bash-4.4$ cmake ../src/ -DHDF5_PATH=/home/beams4/DCHING/Documents/ptychopy/dependLib/hdf5-1.8.13
-- Change Dir: /home/beams4/DCHING/Documents/ptychopy/bin/CMakeFiles/CMakeTmp

Run Build Command(s):/bin/gmake -f Makefile cmTC_523a0/fast && /bin/gmake  -f CMakeFiles/cmTC_523a0.dir/build.make CMakeFiles/cmTC_523a0.dir/build
gmake[1]: Entering directory '/home/beams4/DCHING/Documents/ptychopy/bin/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_523a0.dir/cudaComputeCapability.cpp.o
/bin/c++  -I/usr/local/cuda/include  -o CMakeFiles/cmTC_523a0.dir/cudaComputeCapability.cpp.o -c /home/beams4/DCHING/Documents/ptychopy/src/tools/cudaComputeCapability.cpp
Linking CXX executable cmTC_523a0
/home/beams4/DCHING/miniconda3/envs/ptychopy/bin/cmake -E cmake_link_script CMakeFiles/cmTC_523a0.dir/link.txt --verbose=1
/bin/c++ -rdynamic CMakeFiles/cmTC_523a0.dir/cudaComputeCapability.cpp.o -o cmTC_523a0  -Wl,-rpath,/usr/local/cuda/lib64 /usr/local/cuda/lib64/libcudart.so 
gmake[1]: Leaving directory '/home/beams4/DCHING/Documents/ptychopy/bin/CMakeFiles/CMakeTmp'


-- CUDA COMPUTE CAPABILITY: 6.1
-- SDL2_PATH not set: the package will be built without SDL2 visualization support. SDL2 can be downloaded at http://www.libsdl.org/
-- DIY_PATH not set: the package will be built without DIY2 support. Instructions to download DIY2 can be found at https://github.com/diatomic/diy2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/beams4/DCHING/Documents/ptychopy/bin
(ptychopy) bash-4.4$ make -j 16
[  6%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/cuda_compile_1_generated_DiffractionsKernels.cu.o
[  6%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/cuda_compile_1_generated_DM.cu.o
[ 18%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/cuda_compile_1_generated_SampleKernels.cu.o
[ 18%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/cuda_compile_1_generated_ScanMeshKernels.cu.o
[ 18%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/cuda_compile_1_generated_ProbeKernels.cu.o
[ 18%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/cuda_compile_1_generated_utilitiesKernels.cu.o
/home/beams4/DCHING/Documents/ptychopy/src/utilitiesKernels.cu(1522): warning: invalid narrowing conversion from "double" to "float"

/home/beams4/DCHING/Documents/ptychopy/src/utilitiesKernels.cu(1522): warning: invalid narrowing conversion from "double" to "float"

/home/beams4/DCHING/Documents/ptychopy/src/SampleKernels.cu(316): warning: variable "temp" was declared but never referenced

/home/beams4/DCHING/Documents/ptychopy/src/DM.cu(58): warning: invalid narrowing conversion from "double" to "float"

/home/beams4/DCHING/Documents/ptychopy/src/DM.cu(58): warning: invalid narrowing conversion from "double" to "float"

/home/beams4/DCHING/Documents/ptychopy/src/Cuda2DArray.hpp(556): warning: conversion from a string literal to "char *" is deprecated

/home/beams4/DCHING/Documents/ptychopy/src/Cuda2DArray.hpp(557): warning: conversion from a string literal to "char *" is deprecated

/home/beams4/DCHING/Documents/ptychopy/src/DM.cu(58): warning: invalid narrowing conversion from "double" to "float"

/home/beams4/DCHING/Documents/ptychopy/src/DM.cu(58): warning: invalid narrowing conversion from "double" to "float"

/home/beams4/DCHING/Documents/ptychopy/src/DM.cu: In member function ‘void DM::checkCache(real_t, real_t, bool, bool, bool, bool)’:
/home/beams4/DCHING/Documents/ptychopy/src/DM.cu:58:34: warning: narrowing conversion of ‘(1.0e+0 / ((double)objMax))’ from ‘double’ to ‘real_t’ {aka ‘float’} inside { } [-Wnarrowing]
  real_t passedFactors[2] = {1.0/objMax, 1.0/probeMax};
                            ~~~~~~^~~~~~~~
/home/beams4/DCHING/Documents/ptychopy/src/DM.cu:58:50: warning: narrowing conversion of ‘(1.0e+0 / ((double)probeMax))’ from ‘double’ to ‘real_t’ {aka ‘float’} inside { } [-Wnarrowing]
  real_t passedFactors[2] = {1.0/objMax, 1.0/probeMax};
                                            ~~~~~~^~~~~     
/home/beams4/DCHING/Documents/ptychopy/src/utilitiesKernels.cu(1522): warning: invalid narrowing conversion from "double" to "float"

/home/beams4/DCHING/Documents/ptychopy/src/utilitiesKernels.cu(1522): warning: invalid narrowing conversion from "double" to "float"

/home/beams4/DCHING/Documents/ptychopy/src/utilitiesKernels.cu: In function ‘void h_checkCache(thrust::device_vector<float, thrust::device_allocator<float> >&, thrust::host_vector<bool>&, thrust::host_vector<float>&, thrust::device_vector<bool, thrust::device_allocator<bool> >&, real_t, real_t, bool, bool, bool, bool)’:
/home/beams4/DCHING/Documents/ptychopy/src/utilitiesKernels.cu:1522:34: warning: narrowing conversion of ‘(1.0e+0 / ((double)objMax))’ from ‘double’ to ‘real_t’ {aka ‘float’} inside { } [-Wnarrowing]
  real_t passedFactors[2] = {1.0/objMax, 1.0/probeMax};
                            ~~~~~~^~~~~~~~
/home/beams4/DCHING/Documents/ptychopy/src/utilitiesKernels.cu:1522:50: warning: narrowing conversion of ‘(1.0e+0 / ((double)probeMax))’ from ‘double’ to ‘real_t’ {aka ‘float’} inside { } [-Wnarrowing]
  real_t passedFactors[2] = {1.0/objMax, 1.0/probeMax};
                                            ~~~~~~^~~~~     
[ 21%] Linking kernelsLib
Linking CUDA separable kernels library kernelsLib
[ 24%] Generating CUDA static library kernelsLib
Generating CUDA separable kernels library kernelsLib
ar: /usr/bin/../bin/../lib/bfd-plugins/LLVMgold.so: wrong ELF class: ELFCLASS32

[ 24%] Built target kernelsLib_target
Consolidate compiler generated dependencies of target ptychoLib
[ 36%] Building CXX object CMakeFiles/ptychoLib.dir/CartesianScanMesh.cpp.o
[ 36%] Building CXX object CMakeFiles/ptychoLib.dir/Cuda2DArray.cpp.o
[ 36%] Building CXX object CMakeFiles/ptychoLib.dir/CudaFFTPlan.cpp.o
[ 48%] Building CXX object CMakeFiles/ptychoLib.dir/CudaSmartPtr.cpp.o
[ 48%] Building CXX object CMakeFiles/ptychoLib.dir/Diffractions.cpp.o
[ 48%] Building CXX object CMakeFiles/ptychoLib.dir/DiffractionLoader.cpp.o
[ 48%] Building CXX object CMakeFiles/ptychoLib.dir/FileManager.cpp.o
[ 48%] Building CXX object CMakeFiles/ptychoLib.dir/GLResourceManager.cpp.o
[ 51%] Building CXX object CMakeFiles/ptychoLib.dir/IPtychoScanMesh.cpp.o
[ 57%] Building CXX object CMakeFiles/ptychoLib.dir/IPhaser.cpp.o
[ 57%] Building CXX object CMakeFiles/ptychoLib.dir/ListScanMesh.cpp.o
[ 60%] Building CXX object CMakeFiles/ptychoLib.dir/MLS.cpp.o
[ 63%] Building CXX object CMakeFiles/ptychoLib.dir/MPIPhaser.cpp.o
[ 69%] Building CXX object CMakeFiles/ptychoLib.dir/Probe.cpp.o
[ 72%] Building CXX object CMakeFiles/ptychoLib.dir/RenderServer.cpp.o
[ 72%] Building CXX object CMakeFiles/ptychoLib.dir/Parameters.cpp.o
In file included from /home/beams4/DCHING/Documents/ptychopy/src/DiffractionLoader.cpp:38:
/home/beams4/DCHING/Documents/ptychopy/src/FileManager.h:77: warning: "HAVE_HDF5" redefined
 #define HAVE_HDF5
 
<command-line>: note: this is the location of the previous definition
In file included from /home/beams4/DCHING/Documents/ptychopy/src/FileManager.cpp:35:
/home/beams4/DCHING/Documents/ptychopy/src/FileManager.h:77: warning: "HAVE_HDF5" redefined
 #define HAVE_HDF5
 
<command-line>: note: this is the location of the previous definition
In file included from /home/beams4/DCHING/Documents/ptychopy/src/Diffractions.cpp:43:
/home/beams4/DCHING/Documents/ptychopy/src/FileManager.h:77: warning: "HAVE_HDF5" redefined
 #define HAVE_HDF5
 
<command-line>: note: this is the location of the previous definition
/home/beams4/DCHING/Documents/ptychopy/src/CudaFFTPlan.cpp: In member function ‘cufftHandle CudaFFTPlan::createPlan(cufftType, unsigned int, unsigned int, unsigned int, unsigned int)’:
/home/beams4/DCHING/Documents/ptychopy/src/CudaFFTPlan.cpp:89:25: warning: narrowing conversion of ‘fftH’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
  int dims[] = {fftH,fftW};
                         ^
/home/beams4/DCHING/Documents/ptychopy/src/CudaFFTPlan.cpp:89:25: warning: narrowing conversion of ‘fftW’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
/home/beams4/DCHING/Documents/ptychopy/src/CudaFFTPlan.cpp:90:27: warning: narrowing conversion of ‘fftH’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
  int embed[] = {fftH,pitch};
                           ^
/home/beams4/DCHING/Documents/ptychopy/src/CudaFFTPlan.cpp:90:27: warning: narrowing conversion of ‘pitch’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
[ 75%] Building CXX object CMakeFiles/ptychoLib.dir/Sample.cpp.o
/home/beams4/DCHING/Documents/ptychopy/src/IPtychoScanMesh.cpp: In member function ‘bool IPtychoScanMesh::loadTestIGroup(const char*, std::vector<int>&)’:
/home/beams4/DCHING/Documents/ptychopy/src/IPtychoScanMesh.cpp:392:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
[ 78%] Building CXX object CMakeFiles/ptychoLib.dir/SpiralScanMesh.cpp.o
[ 81%] Building CXX object CMakeFiles/ptychoLib.dir/ThreadPool.cpp.o
[ 84%] Building CXX object CMakeFiles/ptychoLib.dir/Timer.cpp.o
[ 87%] Building CXX object CMakeFiles/ptychoLib.dir/ePIE.cpp.o
[ 90%] Building CXX object CMakeFiles/ptychoLib.dir/utilities.cpp.o
/home/beams4/DCHING/Documents/ptychopy/src/Probe.cpp: In member function ‘bool Probe::initVarModes()’:
/home/beams4/DCHING/Documents/ptychopy/src/Probe.cpp:500:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
[ 93%] Linking CXX static library libptychoLib.a
/bin/ar: /usr/bin/../bin/../lib/bfd-plugins/LLVMgold.so: wrong ELF class: ELFCLASS32

/bin/ranlib: /usr/bin/../bin/../lib/bfd-plugins/LLVMgold.so: wrong ELF class: ELFCLASS32

[ 93%] Built target ptychoLib
Consolidate compiler generated dependencies of target ptycho
[ 96%] Building CXX object CMakeFiles/ptycho.dir/examples/testEPIE.cpp.o
[100%] Linking CXX executable ptycho
[100%] Built target ptycho
```

**Comment by kyuepublic** [comment]
I will look into, but do you get the result saved in the data folder?

**Comment by carterbox** [comment]
Only sim256rDM_object_0.csv  sim256rDM_probes_0.csv were added to the data folder.

**Comment by kyuepublic** [comment]
Right, those are reconstructed object and probe, you can check those files

**Pull request closed without merging**
